services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  GarvinHicking\TcaCountryExample\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/{Model,Validator}'
